### ISSUE TITLE
yaml and gbk

### ISSUE THREAD

**Issue by MiracuSI** [agilescientific/seisplot#44]
problem1: File "seisplot.py", line 433, in <module>
                 cfg = yaml.safe_load(f)
    pyyaml version?
2.
UnicodeDecodeError: 'gbk' codec can't decode byte 0x99 in position 1922: illegal multiby
te sequence

**Comment by kwinkunks** [comment]
Not sure what to make of these; I can't reproduce them. Would need more info.
